@startuml
title Aktivitätsdiagramm – Daten in SQLite speichern

|System (Flask Controller)|
start
:Request verarbeitet (z.B. Kunde anlegen/bearbeiten);
:SQLAlchemy Session öffnen;
:Objekt an DB-Session übergeben (db.session.add);

|SQLite / DB Layer|
:Transaktion vorbereiten;

|System (Flask Controller)|
:db.session.commit();

if (Commit erfolgreich?) then (Ja)
  :Erfolgsmeldung/Weiterleitung;
  stop
else (Nein)
  :db.session.rollback();
  :Fehlermeldung loggen + Flash;
  stop
endif

@enduml